export const DESTINATION_TYPES = {
  FETCH_TREDING_DESTINATIONS_START:
    "destinations/FETCH_TREDING_DESTINATIONS_START",
  FETCH_TREDING_DESTINATIONS_SUCCESS:
    "destinations/FETCH_TREDING_DESTINATIONS_SUCCESS",
  FETCH_TREDING_DESTINATIONS_FAILED:
    "destinations/FETCH_TREDING_DESTINATIONS_FAILED",
  SET_DESTINATIONS_BY_CATEGORY: "destinations/SET_DESTINATIONS_BY_CATEGORY",
};
