export const FAVORITES_ACTION_TYPES = {
    ADD_DESTINATION_TO_FAVORITES: 'favorites/ADD_DESTINATION_TO_FAVORITE',
    REMOVE_DESTINATION_FROM_FAVORITES: 'favorites/REMOVE_DESTINATION_FROM_FAVORITES'
}