export const DESTINATIONS_BY_CATEGORY_TYPES = {
  FETCH_CATEGORIES_START: "categories/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
  SET_CATEGORIES: "categories/SET_CATEGORIES",
  SET_CATEGORY_ACTIVE: 'categories/SET_CATEGORY_ACTIVE'
};
